<?php

/**
 * @file
 * simpleSAMLphp authentication module for Drupal.
 *
 * This authentication module is based on the shibboleth authentication module,
 * with changes to adopt to use simpleSAMLphp.
 *
 * ISSUES and TODOs:
 *  ISSUE: User is always dropped on user page after login, instead of where
 *         they were when they clicked "Federated Log In". Because of this, deep
 *         linking to access controlled content does not work. Usability would
 *         be considerably increased if this were resolved.
 *  FYI: Drupal now requires knowledge of the local user password in order to
 *       change e-mail address, etc. This could be an issue for users of
 *       accounts that are autoprovisioned by this module, though Drupal does
 *       give users the ability to reset their password to something they know
 *       via the Request new password feature.
 *  KLUDGE: Drupal does not kill the session on logout, even with
 *          drupal_session_destroy_uid(), so I had to use session_destroy().
 * @todo Rework the default login limitation logic to use a drupal permission
 *        rather than a list of UIDs.
 * @todo When denying access because the administrator has chosen not to allow
 *        the module to register/create accounts, the user is told to contact
 *        the administrator; the message should provide the contact information.
 *  ISSUE: Until Drupal issue #754560 is resolved users will not see logout
 *         notices.
 */

use Drupal\Core\Url;
use \Drupal\Core\Form\FormStateInterface;
use \Drupal\simplesamlphp_auth\SimplesamlphpAuthManager;

/**
 * Implements hook_help().
 */
function simplesamlphp_auth_help($route_name) {
  switch ($route_name) {
    case 'simplesamlphp_auth.admin_settings':
    case 'help.page.simplesamlphp_auth':
      $output = t('<p>This module integrates Drupal with a SimpleSAMLphp Service Point (SP), effectively federating Drupal.</p>');

      return $output;
  }
}

/**
 *  Implements hook_user_login().
 */
function simplesamlphp_auth_user_login($account) {

  $simplesaml = \Drupal::service('simplesamlphp_auth.manager');

  if (!$simplesaml->isActivated()) {
    return;
  }

  // If user registration has a valid session...
  if ($simplesaml->isAuthenticated() && $simplesaml->getAuthname() == $account->getInitialEmail()) {
    // Get name and mail from default attributes.
    try {
      $name = $simplesaml->getDefaultName();
      $mail = $simplesaml->getDefaultEmail();
    } catch (Exception $e) {
      drupal_set_message(t('Your user name was not provided by your identity provider (IDP).'), "error");
//      watchdog('simplesamlphp_auth', $e->getMessage(), NULL, WATCHDOG_CRITICAL);
    }

    // Update username and email address.
    // @TODO Make this conditional.
    // Should this go in the Manager (externalLogin method)
    $account->setUsername($name);
    $account->setEmail($mail);
    $account->save();

  }
}

/**
 *  Implements hook_user_logout().
 */
function simplesamlphp_auth_user_logout($account) {

  $config = \Drupal::config('simplesamlphp_auth.settings');
  $logout_url = $config->get('logout_goto_url');
  if ($logout_url) {
    // $simplesaml->logout($logout_url);
  }

  return;
  _simplesaml_auth_autoload();

  if (!empty($_simplesamlphp_auth_saml_attributes)) {

    $config = SimpleSAML_Configuration::getInstance();

    // :KLUDGE: for some reason Drupal is not killing the session, even if I were to call drupal_session_destroy_uid() here.
    session_destroy();

    $gotourl = base_path();
    if (variable_get('simplesamlphp_auth_logoutgotourl', '')) {
      $gotourl = variable_get('simplesamlphp_auth_logoutgotourl', '');
    }

    $_simplesamlphp_auth_as->logout($gotourl);

  }
}

/**
 *  Implements hook_user_cancel().
 */
function simplesamlphp_auth_user_cancel($edit, $account, $method) {
  db_delete('simplesamlphp_auth_authmap')
    ->condition('uid', $account->id())
    ->execute();
}

/**
 *  Implements hook_form_FORM_ID_alter().
 *
 * Alters the user register form to include a checkbox signifying the user
 * should be SimpleSAML enabled. Removes password fields if the IdP
 * is the sole place for password management.
 *
 * @see AccountForm::form()
 * @see simplesamlphp_auth_user_form_submit()
 */
function simplesamlphp_auth_form_user_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  simplesamlphp_auth_user_form_includes($form);

  // If the user has a simplesamlphp_auth authmap record, then don't require
  // them to know their Drupal password. This will allow them to change their
  // e-mail address, and set a Drupal password if they want to (and are allowed).
  $account = $form_state->getFormObject()->getEntity();
  $saml_enabled = db_query("SELECT authname FROM {simplesamlphp_auth_authmap} WHERE authname = :authname", array(':authname' => $account->getInitialEmail()))->fetchField();
  if ($saml_enabled) {
    $form['simplesamlphp_auth_user_enable']['#default_value'] = TRUE;
    unset($form['account']['current_pass']);
    unset($form['account']['current_pass_required_values']);
    $form['#validate'] = array_diff($form['#validate'], array('user_validate_current_pass'));

    // If the user is a simplesamlphp_auth user and is NOT allowed to set their Drupal password, remove the fields from the form.
    $config = \Drupal::config('simplesamlphp_auth.settings');
    if (!$config->get('allow.set_drupal_pwd')) {
      unset($form['account']['pass']);
    }
  }
}

/**
 *  Implements hook_form_FORM_ID_alter().
 *
 * Alters the user register form to include a checkbox signifying the user
 * should be SimpleSAML enabled.
 *
 *
 * @see AccountForm::form()
 * @see simplesamlphp_auth_user_form_submit()
 */
function simplesamlphp_auth_form_user_register_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  simplesamlphp_auth_user_form_includes($form);
  $form['simplesamlphp_auth_user_enable']['#default_value'] = TRUE;
}

/**
 * Helper function to include the SimpleSAML checkbox on user forms.
 *
 * @param $form
 *
 * @see simplesamlphp_auth_form_user_form_alter()
 * @see simplesamlphp_auth_form_user_register_form_alter()
 */
function simplesamlphp_auth_user_form_includes(&$form) {
  $form['simplesamlphp_auth_user_enable'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable this user to leverage SAML authentication'),
  );

  $form['actions']['submit']['#submit'][] = 'simplesamlphp_auth_user_form_submit';
}

/**
 *  Implements hook_form_FORM_ID_alter().
 */
function simplesamlphp_auth_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  // Return without executing if the functionality is not enabled.
  if (!\Drupal::config('simplesamlphp_auth.settings')->get('activate')) {
    return;
  }

  $link = \Drupal::url('simplesamlphp_auth.saml_login');

  $form['simplesamlphp_auth_login_link'] = array(
    '#markup' => \Drupal::l(t('Fedarated Log In'), new Url('simplesamlphp_auth.saml_login', array(), array(
    'attributes' => array(
      'class' => array('simplesamlphp-auth-login-link'),
    ),
  ))));

}

/**
 * Form submission handler for user_form.
 *
 * @see simplesamlphp_auth_form_user_register_form_alter()
 * @see simplesamlphp_auth_form_user_form_alter()
 */
function simplesamlphp_auth_user_form_submit($form, FormStateInterface $form_state) {

  // Enter the user's authname into the simplesamlphp_auth_authmap table.
  if ($form_state->getValue('simplesamlphp_auth_user_enable')) {
    $account = $form_state->getFormObject()->getEntity();
    db_merge('simplesamlphp_auth_authmap')
      ->key(array(
        'uid' => $form_state->getValue('uid'),
      ))
      ->fields(array(
        'authname' => $account->getInitialEmail(),
      ))
      ->execute();
  }
  // Remove this username from the simplesamlphp_auth_authmap table.
  else {
    db_delete('simplesamlphp_auth_authmap')
      ->condition('uid', $form_state->getValue('uid'))
      ->execute();
  }
}

/****************************************************************************
 * Private functions ********************************************************
 ****************************************************************************/

/**
 * Generates the text for the log in block.
 */
function _simplesamlphp_auth_generate_block_text() {
  global $_simplesamlphp_auth_as;
  $block_content = '';
  global $user;

  if (!_simplesamlphp_auth_isEnabled()) {
    // Exit without executing.
    return;
  }

  // Check if valid local session exists..
  if ($_simplesamlphp_auth_as->isAuthenticated()) {
    $block_content .= '<p>Logged in as: ' . $user->name . '<br />' . l('Log Out', 'user/logout') . '</a></p>';
  }
  else {
    $block_content .= '<p>' . l('Federated Log In', 'saml_login') . '</p>';
  }

  return $block_content;
}

/**
 * Evaluates a role rule.
 *
 * @param $roleruleevaluation
 *   An array containing the role rule to evaluate.
 * @param $attributes
 *   An array containing the identity attributes.
 *
 * @return
 *   An array containing role value and the attribute, or FALSE.
 */
function _simplesamlphp_auth_evaulaterolerule($roleruleevaluation, $attributes) {
  _simplesaml_auth_debug(t('Evaluate rule (key=%key,operator=%op,value=%val)', array(
    '%key' => $roleruleevaluation[0],
    '%op' => $roleruleevaluation[1],
    '%val' => $roleruleevaluation[2]
  )));

  if (!array_key_exists($roleruleevaluation[0], $attributes)) {
    return FALSE;
  }
  $attribute = $attributes[$roleruleevaluation[0]];

  switch ($roleruleevaluation[1]) {
    case '=' :
      return in_array($roleruleevaluation[2], $attribute);

    case '@=' :
      $dc = explode('@', $attribute[0]);
      if (count($dc) != 2) {
        return FALSE;
      }

      return ($dc[1] == $roleruleevaluation[2]);
    case '~=':
      foreach ($attribute as $subattr) {
        $pos = strpos($subattr, $roleruleevaluation[2]);
        if ($pos !== FALSE) {
          return TRUE;
        }
      }
      return FALSE;
  }

  return FALSE;
}

/**
 * Performs role population.
 *
 * @param $rolemap
 *   A string containing the role map.
 *
 * @return
 *   An array containing user's roles.
 */
function _simplesamlphp_auth_rolepopulation($rolemap) {
  return;
  global $_simplesamlphp_auth_as;
  global $_simplesamlphp_auth_saml_attributes;
  $roles = array();

  _simplesaml_auth_debug(t('Rolemap: %rolemap', array('%rolemap' => $rolemap)));

  // Check if valid local session exists..
  if ($_simplesamlphp_auth_as->isAuthenticated()) {
    $attributes = $_simplesamlphp_auth_saml_attributes;

    if (empty($rolemap)) {
      return $roles;
    }

    _simplesaml_auth_debug(t('Evaluate rolemap: %rolemap', array('%rolemap' => $rolemap)));

    $rolerules = explode('|', $rolemap);

    foreach ($rolerules AS $rolerule) {
      _simplesaml_auth_debug(t('Evaluate role rule: %rolerule', array('%rolerule' => $rolerule)));

      $roleruledecompose = explode(':', $rolerule);

      $roleid = $roleruledecompose[0];
      $roleruleevaluations = explode(';', $roleruledecompose[1]);

      $addnew = TRUE;
      foreach ($roleruleevaluations AS $roleruleevaluation) {

        _simplesaml_auth_debug(t('Evaluate role evaulation: %roleruleeval', array('%roleruleeval' => $roleruleevaluation)));

        $roleruleevaluationdc = explode(',', $roleruleevaluation);
        if (!_simplesamlphp_auth_evaulaterolerule($roleruleevaluationdc, $attributes)) {
          $addnew = FALSE;
        }
      }
      if ($addnew) {
        $roles[$roleid] = $roleid;
        _simplesaml_auth_debug(t('Add new role: %roleid', array('%roleid' => $roleid)));
      }

    }
  }

  return $roles;
}

/**
 * This helper function is used by developers to debug the form API workflow in this module.
 */
function _simplesaml_auth_debug($message) {
  watchdog('simplesamlphp', $message, NULL, WATCHDOG_DEBUG);
}

/**
 * Helper function for logging out a user that is has a active session in Drupal but not with simpleSAML.
 */
function _simplesamlphp_auth_destroy_drupal_session() {
  global $user;

  watchdog('user', 'Session closed for %name.', array('%name' => $user->name));

  // Destroy the current session:
  session_destroy();
  drupal_save_session(FALSE);

  // Only variables can be passed by reference workaround.
  $NULL = NULL;
  user_module_invoke('logout', $NULL, $user);

  // Load the anonymous user.
  $user = drupal_anonymous_user();

  drupal_goto();
}
